import type { Metadata } from 'next'

import '../globals.css'
import UserNav from '@/components/courses/UserNav'
import SideBar from '@/components/courses/SideBar'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className=' bg-[#00122C]'>
				<SideBar />
				<UserNav />
				<div className=' py-[10rem] w-[80vw] mx-auto max-sm:w-[90vw]'>
					{children}
				</div>
			</body>
		</html>
	)
}
