import type { Metadata } from 'next'

import '../globals.css'
import UserNav from '@/components/courses/UserNav'
import SideBar from '@/components/courses/SideBar'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<SideBar />
				<UserNav />
				<div className=' '>{children}</div>
			</body>
		</html>
	)
}
